In [1]:
import tensorflow as tf
import os
import time
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
from nilearn import image
from nilearn import plotting
import nibabel as nib
from nilearn.plotting import plot_stat_map, plot_anat, plot_img
from nilearn.image import concat_imgs, mean_img
import nibabel as nib

Matplotlib created a temporary config/cache directory at /tmp/pbs.3722132.pbsha.ib.sockeye/matplotlib-3sugmc3i because the default path (/home/mkhademi/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.


In [2]:
data_dir = '/arc/project/st-ipor-1/mkhademi/BOLD5000_2.0/'
img = nib.load(data_dir + 'CSI1_brainmask.nii.gz')
data = img.get_fdata()
print(data)
print(data.shape)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
(71, 89, 7

In [3]:
file_name = data_dir + 'BOLD5000_GLMsingle_ROI_betas/py/' + 'CSI1_GLMbetas-TYPED-FITHRF-GLMDENOISE-RR_allses_LHEarlyVis.npy'
roi_LHEarlyVis = np.load(file_name)
print(roi_LHEarlyVis)
print(roi_LHEarlyVis.shape)
file_name = data_dir + 'BOLD5000_GLMsingle_ROI_betas/py/' + 'CSI1_GLMbetas-TYPED-FITHRF-GLMDENOISE-RR_allses_LHLOC.npy'
roi_LHLOC = np.load(file_name)
print(roi_LHLOC.shape)
file_name = data_dir + 'BOLD5000_GLMsingle_ROI_betas/py/' + 'CSI1_GLMbetas-TYPED-FITHRF-GLMDENOISE-RR_allses_LHOPA.npy'
roi_LHOPA = np.load(file_name)
print(roi_LHOPA.shape)

[[ 0.16727145  1.1733775  -0.48282975 ...  0.65440243  1.2773808
   0.7152166 ]
 [ 1.2589841   0.74470425  0.26411656 ...  1.5145518   0.74498016
   0.88225025]
 [ 0.27966648 -0.16489185 -0.55047363 ... -0.11178026 -1.3599519
  -1.125909  ]
 ...
 [-2.380134   -0.41993752 -0.15568627 ...  0.8511743   1.0023801
   0.6667326 ]
 [-1.4258239  -0.01796909 -0.5075829  ...  0.6927651   1.0405765
   1.0964348 ]
 [-2.3990953   0.37309152  0.5922054  ...  0.6982572   0.04399459
  -0.03115825]]
(5254, 210)
(5254, 152)
(5254, 101)
